# Generated by Django 5.2.3 on 2025-06-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="available_sizes",
            field=models.JSONField(default=list),
        ),
    ]
