# Generated by Django 5.2.3 on 2025-06-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_review_sentiment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="sentiment",
            field=models.CharField(
                choices=[
                    ("Positive", "Positive"),
                    ("Negative", "Negative"),
                    ("Neutral", "Neutral"),
                ],
                default="Neutral",
                max_length=10,
            ),
        ),
    ]
