# Generated by Django 5.2.3 on 2025-06-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_review_sentiment"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sale_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
