# Generated by Django 5.2.3 on 2025-06-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_product_sale_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                help_text="Description generated by LLaMA AI for accurate and engaging content."
            ),
        ),
    ]
