# Generated by Django 5.2.3 on 2025-06-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_sitetheme_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitetheme",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="sitetheme",
            name="name",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark"), ("custom", "Custom")],
                max_length=20,
                unique=True,
            ),
        ),
    ]
