# Generated by Django 5.2.3 on 2025-07-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_abandonedcart"),
    ]

    operations = [
        migrations.AddField(
            model_name="abandonedcart",
            name="cart_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="abandonedcart",
            name="emailed",
            field=models.BooleanField(default=False),
        ),
    ]
