# Generated by Django 5.2.3 on 2025-07-02 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0016_abandonedcart_cart_data_abandonedcart_emailed"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitorProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("competitor_url", models.URLField()),
                (
                    "latest_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("last_checked", models.DateTimeField(auto_now=True)),
                (
                    "your_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
            ],
        ),
    ]
